name: fscl-proc-db
services: 
  db:
    image: postgres:17
    restart: always 
    environment:
      - POSTGRES_PASSWORD=fscl
    networks:
      - server-net
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  server-net: {}
volumes:
  db-data: {}
